export const auth = {
	AUTH_START: 'AUTH_START',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_FAIL: 'AUTH_FAIL',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAIL: 'SIGN_UP_FAIL',
	LOGOUT: 'LOGOUT'
};

export const hospital = {
	FETCH_START: 'FETCH_START',
	FETCH_SUCCESS: 'FETCH_SUCCESS',
	FETCH_FAIL: 'FETCH_FAIL'
};